apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grpc-gateway-sample-ojmj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grpc-gateway-sample-ojmj
    app.kubernetes.io/part-of: grpc-gateway-sample
  name: grpc-gateway-sample-ojmj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: grpc-gateway-sample-ojmj
      app.kubernetes.io/name: tekton-results-api-14
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: grpc-gateway-sample-ojmj
        app.kubernetes.io/name: tekton-results-api-14
    spec:
      containers:
      - args:
        - -grpc-server-endpoint
        - grpc-gateway-sample-2.oandriie-tenant.svc.cluster.local:50051
        image: quay.io/redhat-user-workloads-stage/oandriie-tenant/grpc-gateway-sample/grpc-gateway-sample-ojmj@sha256:3de7cc7d184a10a59f99c46b8dd4736a2b24c0b03cfb2388d7e74f544c04d17a
        name: my-nodejs
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: grpc-gateway-sample-2
status: {}
